apiVersion: actions.summerwind.dev/v1alpha1
kind: RunnerDeployment
metadata:
  name: example-runnerdeploy2
spec:
  replicas: 1
  template:
    spec:
      repository: cenkkg/GithubActionsDemo
      labels:
        - "actions_runner_all_tests"