name: Python Unit Tests With GitHub Packets
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]


jobs:
  test:
    name: Unit Tests
    runs-on: self-hosted
    steps:
      - name: Dummy GitHub Actions Test
        run: |
          echo "Dummy Test"
        shell: bash