name: Selenium Tests
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    name: Selenium Tests
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Python and pip
        run: |
          sudo apt-get update
          sudo apt-get install -y python3 python3-pip
          pip3 install --upgrade pip
        shell: bash

      - name: Install dependencies
        run: |
          pip install -r DemoProject/requirements.txt
          sudo apt-get install -y libpango1.0-0 libpangocairo-1.0-0 libpangoft2-1.0-0 libasound2
          sudo apt-get install -y libcups2 libxkbcommon0 libxcomposite1 libxdamage1 libxrandr2 libgbm1 libatk1.0-0 libatk-bridge2.0-0 libnss3 xvfb 

      - name: Set up Chrome
        uses: browser-actions/setup-chrome@latest

      - name: Display Chrome Version
        run: ${{ steps.setup-chrome.outputs.executablePath }} --version

      - name: Start application
        run: |
          cd DemoProject
          python main.py &
          sleep 2  # give the application some time to start

      - name: Run tests
        run: |
          cd DemoProject/tests
          xvfb-run python -m unittest selenium_check_city.py
        env:
          CHROME_BIN: ${{ steps.setup-chrome.outputs.executablePath }}
