name: Push to ACR
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    name: Selenium Tests
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Python and pip
        run: |
          sudo apt-get update
          sudo apt-get install -y python3 python3-pip
          pip3 install --upgrade pip
        shell: bash

      - name: Install dependencies
        run: |
          python3 -m pip install --upgrade pip
          pip install -r DemoProject/requirements.txt

      - name: Set up Chrome
        uses: browser-actions/setup-chrome@latest

      - name: Install dependencies
        run: |
          sudo apt-get install -y xvfb
          python -m pip install --upgrade pip

      - name: Start application
        run: |
          cd DemoProject
          python main.py &
          sleep 2  # give the application some time to start

      - name: Run tests
        run: |
          cd DemoProject/tests
          xvfb-run python -m unittest selenium_check_city.py
        env:
          CHROME_BIN: ${{ steps.setup-chrome.outputs.executablePath }}



