name: SonarQube Test
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    name: Build
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Python and pip
        run: |
          sudo apt-get update
          sudo apt-get install -y python3 python3-pip
          pip3 install --upgrade pip
        shell: bash

      - name: Install dependencies
        run: |
          python3 -m pip install --upgrade pip
          pip install -r DemoProject/requirements.txt

      - name: Install dependencies
        run: |
          python3 -m pip install --upgrade pip
          pip install -r DemoProject/requirements.txt

      - name: Run unit tests
        run: |
          cd DemoProject/tests
          python3 test_runner.py

      - name: Install SonarScanner CLI
        run: |
          curl -L -o sonar-scanner-cli.zip https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-4.6.2.2472-linux.zip
          unzip sonar-scanner-cli.zip
          rm sonar-scanner-cli.zip

      - name: Run SonarQube Scanner
        run: |
          ./sonar-scanner-4.6.2.2472-linux/bin/sonar-scanner \
            -Dsonar.projectKey=GithubActionsDemo \
            -Dsonar.host.url=http://sonarqube-service.actions-runner-system.svc.cluster.local:9000 \
            -Dsonar.login=squ_ebd8195c164b1c811e5a9e95a2a2755b0d5496b3

