name: Build
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    name: Build
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Python and pip
        run: |
          sudo apt-get update
          sudo apt-get install -y python3 python3-pip
          pip3 install --upgrade pip
        shell: bash

      - name: Install dependencies
        run: |
          python3 -m pip install --upgrade pip
          pip install -r DemoProject/requirements.txt

      - name: Install dependencies
        run: |
          python3 -m pip install --upgrade pip
          pip install -r DemoProject/requirements.txt

      - name: Run unit tests
        run: |
          cd DemoProject/tests
          python3 test_runner.py

      - name: SonarQube Scan
        env:
          SONAR_TOKEN: sonar.allowPermissionManagementForProjectAdmins
          SONAR_PROJECT_KEY: GithubActionsDemo
        run: |
          sonar-scanner \
            -Dsonar.projectKey=${SONAR_PROJECT_KEY} \
            -Dsonar.sources=. \
            -Dsonar.language=python \
            -Dsonar.host.url=http://sonarqube-service.default.svc.cluster.local \
            -Dsonar.login=${SONAR_TOKEN}

